### ISSUE TITLE
DLL Build fails when path contains a space

### ISSUE THREAD

**Issue by schultzcole** [KuraiAndras/UnityCsprojNuget#12]
If the path to a user's unity project contains a space, the call to `dotnet build` when generating DLLs will fail with error MSB1008 "Only one project can be specified."

This should be possible to fix by surrounding the path in quotes here: https://github.com/KuraiAndras/UnityCsprojNuget/blob/0a27fb0d020ce5a5d55257180b18a5408401a1da/UnityCsprojNuget/Assets/UnityCsprojNuget.Editor/Application/ProjectBuilder.cs#L38

**Comment by KuraiAndras** [comment]
Version 2.0.1 should fix this, it will be available on openupm momentarily. If the new version fixes your problem, please close this issue.

**Comment by schultzcole** [comment]
Yep, that solved the problem, thanks!
